### ISSUE TITLE
Implement cfgfile-backed profile support for multiple Ravello logins

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#120]
For example, you could have this in `~/.ravshello/config.yaml`:

```
userProfiles:
    r1:
        ravelloUser: rsaw@example.com
        ravelloPass: xxxxx
    p2:
        ravelloUser: rsaw+junk@example.com
        ravelloPass: xxxxx
    blah:
        ravelloUser: ryan@example.net
        ravelloPass: xxxxx
    defaultProfile: p2
```

Then you could pass `-P r1` or `--profile blah` to have ravshello use those creds. Otherwise it would us ethe creds in the one named "p2".

We would still support the current use of `ravelloUser` and `ravelloPass` outside of profiles. If those are present, we could make them trump the `defaultProfile` option.
