### ISSUE TITLE
[RFE] create new applications in a costBucket

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#155]
A new Ravello feature is now available called "billing buckets" https://support.ravellosystems.com/hc/en-us/articles/226449728-Tracking-Your-Ravello-Cloud-Usage-with-Cost-Monitoring-Buckets (costBucket in api documentation)

I would like to see ravshello support the ability to publish applications to a billing bucket.

The costBucket is defined in https://www.ravellosystems.com/ravello-api-doc/#create-application as:

> A structure containing the cost bucket ID for this application. If no ID is specified, the organization cost bucket is used, provided the user has EXECUTE permissions on this bucket.

I would like to see ravshello have a new configuration option that would allow for one to define the costBucket to use when creating applications.

**Comment by ryran** [comment]
@ajblum sorry I never responded. We can TOTALLY do this sometime soon. If you have a specific time-table/deadline, please let me know.

**Comment by ryran** [comment]
Hey @ajblum I'm implementing this today via a new config-file entry which can even be used on a per-profile basis. Excerpt from updated `config.yaml` file:

```yaml
######
## Optionally specify a default cost bucket in which to place all new apps
## created by ravshello. You can use cost bucket name if your user has blanket
## read access to all cost buckets; otherwise, you will need to specify the
## numeric cost bucket ID. In both cases, you will need execute permission on
## the cost bucket in order to associate an app with it.

appCostBucket: myCostBucketNameOrId


######
## Optionally declare MULTIPLE sets of Ravello credentials and map them to
## profile names. The names are arbitrary and can be selected by use of
## the -u or --user cmdline option. Notes:
##  - *ravelloUser* is required.
##  - *ravelloPass* is not required. (Will be prompted for pass.)
##  - *nickname* is not required.
##  - *appCostBucket* is not required.
##  - *defaultProfile* is not required.

#userProfiles:
    bob:
        ravelloUser: bob@example.com
        ravelloPass: xxxxx
        appCostBucket: QA
    ana:
        ravelloUser: anabanana@example.com
        ravelloPass: xxxxx
        nickname: ana
        appCostBucket: DEV
    wow@example:
        ravelloUser: wow@example.com
    defaultProfile: ana
```

As it stands now, if you specify a value for `appCostBucket` in the config file, ravshello automatically tries to put new apps in that cost bucket. This is done toward the end of the `/applications/new` command -- prior to publishing. If it fails, warnings are printed, but the application is still published.

Take a look at this demonstration of how it's handled and let me know if you have any feedback.

![costbuckets](https://user-images.githubusercontent.com/1092618/28242115-2fd51d1a-6971-11e7-9c91-d35afecd765d.png)
