### ISSUE TITLE
Add config directive to allow custom app name prefixes (namespacing) instead of "k:"

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#175]
To explain what ravshello does now, here's an excerpt from the help page:

```
  -k, --nick NICK       Explicitly specify a nickname to use for app-filtering
                        (nickname is normally determined from the system user
                        name and is used to hide applications that don't start
                        with 'k:NICK__'; any apps created will also have that
                        tag prefixed to their name)
```

The `k` originated from when ravshello was just an internal project at Red Hat and the "system user" was a kerberos user.

What I want to do is add a config directive that lets you specify something else instead of `k`. This could be valuable if your account uses namespace prefixes to keep apps separate, e.g.:

- all dev apps might be prefixed with `DEV:`
- all stage apps might be prefixed with `STAGE:`
- all prod apps might be prefixed with `PROD:`

**Comment by ryran** [comment]
Excerpt from updated `config.yaml`:

```yaml
######
## If *appnameNickPrefix* is omitted, it defaults to "k:" (originally for
## "kerberos"). This is used in concert with *nickname* to build a prefix for
## all application names, i.e., a new app created by ravshello will be named:
##    <appnameNickPrefix><nickname>__<APPLICATION_NAME>
## Furthermore, in ravshello you will only be able to see apps whose names
## begin with:
##    <appnameNickPrefix><nickname>__
## Though of course in ravshello, it will hide the prefix so you'll only see:
##    <APPLICATION_NAME>

appnameNickPrefix: 'k:'

# ...

######
## Optionally declare MULTIPLE sets of Ravello credentials and map them to
## profile names. The names are arbitrary and can be selected by use of
## the -u or --user cmdline option. Notes:
##  - *ravelloUser* is required.
##  - *ravelloPass* is not required. (Will be prompted for pass.)
##  - *nickname* is not required.
##  - *appnameNickPrefix* is not required.
##  - *appCostBucket* is not required.
##  - *defaultProfile* is not required.

userProfiles:
    bob:
        ravelloUser: bob@example.com
        ravelloPass: xxxxx
        appCostBucket: QA
        appnameNickPrefix: 'QA:'
    ana:
        ravelloUser: anabanana@example.com
        ravelloPass: xxxxx
        nickname: ana
        appCostBucket: DEV
        appnameNickPrefix: 'DEV:'
    wow@example:
        ravelloUser: wow@example.com
    defaultProfile: ana
```
Excerpt from updated help page:

```
  -k, --nick NICK       Explicitly specify a nickname to use for app-filtering
                        (nickname is normally determined from the system user
                        name and is used to hide applications that don't start
                        with 'k:NICK__'; any apps created will also have that
                        tag prefixed to their name; see also 'nickname' and
                        'appnameNickPrefix' config directives in
                        /usr/share/ravshello/config.yaml)
```
